### ISSUE TITLE
Work on a responsive design for the WDX180 and the Table of Contents

### ISSUE THREAD

**Issue by kostasx** [in-tech-gration/WDX-180#13]
There's an issue with the responsive version of the side Table of Contents menu on some screen sizes (see attached screenshot):

![Screenshot 2023-10-03 at 12 41 07](https://github.com/in-tech-gration/WDX-180/assets/1638325/d9a24c2e-048d-440d-b37f-795c8b54ec73)

To see the issue, visit the following link: [https://in-tech-gration.github.io/WDX-180/curriculum/week01/](https://in-tech-gration.github.io/WDX-180/curriculum/week01/)

**Requirements:**

- Work on a responsive side menu
- Create a branch named `feature/responsive-toc` before starting to work on the task
- Contact the project manager (@kostasx) for more information

**UPDATE 06/10/2023**: 

"The problem regarding responsiveness persists on smaller screens because of this back button doesn't work properly."

**Comment by Sha-Shak** [comment]
Can you please check and let me know if I need to change anything?

**Comment by kostasx** [comment]
Yep, this is a good start. Looks good so I'm opening a PR and merging.

Thanks! :)

**Comment by MaryRichelle** [comment]
The problem regarding responsiveness persists  on smaller screens because of this back button doesn't work properly.

**Comment by kostasx** [comment]
Thank you @MaryRichelle. Re-opening this issue and updating the description.

**Comment by kostasx** [comment]
Can you share some screenshots that can help us pinpoint the responsive issues @MaryRichelle?

**Comment by MaryRichelle** [comment]
### this is for screens 1max-width: 1245 pixels 
![responsiveness-issue](https://github.com/in-tech-gration/WDX-180/assets/71798304/0e638e15-7119-431b-a105-9095241f12e4)
### on screen 850px and less 
![on-tablet](https://github.com/in-tech-gration/WDX-180/assets/71798304/be2332dd-ee7d-422f-9ce9-cb43f15fe310)
when the user's browser is at 100% zoom and responsive
### if you consider users with accessibility needs who may need to zoom in back button doesn't work table of content overlap 
![Web Development X - 180° _ WDX-180](https://github.com/in-tech-gration/WDX-180/assets/71798304/306a4ae9-716f-455e-aad5-0a72ae98a5d8)
