### ISSUE TITLE
Review Week 01

### ISSUE THREAD

**Issue by Jeelex** [in-tech-gration/WDX-180#5]
https://github.com/in-tech-gration/WDX-180/tree/main/curriculum/week01

**Comment by kostasx** [comment]
We're almost ready to start. Any updates on this one @Jeelex ?

**Comment by Jeelex** [comment]
My previous observations seem to have been fixed and everything looks good! 💪 
The only styling issue I've noticed is that the table of contents seems to be overflowing as seen in the screenshots below:

![image](https://github.com/in-tech-gration/WDX-180/assets/46877423/1eee3544-2fe1-416e-a7b5-cb1d934d4d1d)

![image](https://github.com/in-tech-gration/WDX-180/assets/46877423/fd211b8e-c80c-4b8a-923b-30caf8c308dd)


This is an issue for another task so break a leg!!! 🤞

**Comment by kostasx** [comment]
Thank you @Jeelex!
