### ISSUE TITLE
Review Week 03

### ISSUE THREAD

**Issue by asterisg** [in-tech-gration/WDX-180#8]
Review the content of Week 03

- [x] Read every day's content
- [x] Read/Do every day's exercises
- [x] Check links

Please make any suggestions for adding/removing content on each day.
Please point out any mistake found on any file of Week 03.

**Comment by Sha-Shak** [comment]
Issue #1 
Week 03 Day 1's link isn't working under the Exercise Section. [https://github.com/in-tech-gration/WDX-180/blob/main/user/week01/progress/progress.w03.d01.csv](url)

**Comment by Sha-Shak** [comment]
Issue #1 W3-D2
**File Path:** curriculum/week03/exercises/styling_a_biography_page/README.md
**Section:** Starting Point
**Description:** The URL [https://github.com/in-tech-gration/WDX-180/blob/main/curriculum/week03/exercises/styling_a_biography_page/assets/blog-download.html](url) isn't working.

**Comment by Sha-Shak** [comment]
Issue #2 W3-D2
**File Path:** curriculum/week03/exercises/styling_a_biography_page/README.md
**Section:** Example
**Description:** Progress Sheet link isn't working.

**Comment by patric94** [comment]
Thanks for the info Shariar! Updated the main repo and those issues are fixed.

FYI pogress sheet links are linking to files that the users have to create, so if there is a 404 error when clicking on the link, it's gonna work as a reminder to create such file as per instructions.

If you do not have any more comments, tell me to close this issue! :)

**Comment by Sha-Shak** [comment]
Welcome 😄 
Well, I'm not done yet. 
**Issue #3 W3-D3**
> **File Path:** WDX-180/curriculum/week03/resources/css_building_blocks/css_selectors/README.md
**Section:** Selector Lists
**Description:** If I'm understanding it correctly, you want to load the site in the readme. The iframe isn't doing anything. The link works fine but the iframe is just text. Maybe GitHub isn't rendering because of security measures?

**Comment by patric94** [comment]
Hello!

Yeah that's a GitHub issue for security measures.
In the future we would like to find a way to have live examples displayed properly, in markdown files, on GitHub.
